---
# defaults file for fw_rules

fw_request:
  tenant: az-newsub1
  filter: tcpsnow
  rules:
  - { src: [ '10.1.1.1', '10.5.3.2' , '10.54.6.5' ],
      dst: [ '172.26.44.25' ],
      proto: tcp,
      ports: [ "21", "25", "36", "39-99" ] }
  - { src: [ '10.2.3.4' ],
      dst: [ '55.5.1.2', '55.5.1.3' ],
      proto: udp,
      ports: [ "23", "80", "443", "8443-8444" ] }
